### ISSUE TITLE
Confusion about connectionOpenAck in IBCConnection.sol

### ISSUE THREAD

**Issue by michwqy** [hyperledger-labs/yui-ibc-solidity#168]
I found that ```connection.state``` allowed to be ```INIT``` or ```TRYOPEN``` in ```connectionOpenAck``` function of [contracts/core/03-connection/IBCConnection.sol](https://github.com/hyperledger-labs/yui-ibc-solidity/blob/main/contracts/core/03-connection/IBCConnection.sol). I don't understand when ```connection.state``` is ```TRYOPEN``` and ```connectionOpenAck``` can be executed successfully. Since ```connectionOpenAck``` requires counterparty connection in ```TRYOPEN``` state, ```connectionOpenTry``` requires conterparty connection in ```INIT``` state and there is no way that connection can go to ```TRYOPEN``` from ```INIT```, I think  ```connectionOpenAck``` can't be executed successfully if ```connection.state``` is ```TRYOPEN```. Is there any purpose I don't understand?

**Comment by bluele** [comment]
Thank you for opening an issue.

In conclusion, this is a bug.

In [previous versions(e.g. v1.0.0) of ibc-go](https://github.com/cosmos/ibc-go/blob/e9f1dc2a4f8631749c72e48957848cab3eb10762/modules/core/03-connection/keeper/handshake.go#L225), it was possible for a chain that executed `ConnOpenInit` to execute `ConnOpenTry` by referencing a previous connection. Consequently, there could be both `INIT` and `TRY_OPEN` as a previous connection state on `ConnOpenAck`.

However, the latest ics-03 does not support referencing a previous connection on `ConnOpenTry`, so only `INIT` should be allowed as a previous state on `ConnOpenACK`. Therefore, ibc-solidity needs to be fixed in the same way.

**Comment by michwqy** [comment]
Thanks for your reply.
