### ISSUE TITLE
IBCHandler::sendMessage method accepting google protobuf ``Any`` to dispatch messages

### ISSUE THREAD

**Issue by lightyear15** [hyperledger-labs/yui-ibc-solidity#66]
there should be a general entry point able to receive an ``Any``  protobuf message to collect and dispatch all the messages sent to the IBC Handler by a relayer, as the cosmos client has. 
Just to give a few references, looking at hermes, one of the most trending ibc relayer implementation: 
https://docs.rs/ibc-relayer/0.8.0/ibc_relayer/chain/trait.ChainEndpoint.html#tymethod.send_messages_and_wait_commit 
https://docs.rs/ibc-relayer/0.8.0/src/ibc_relayer/chain/cosmos.rs.html#874-928

**Comment by siburu** [comment]
@lightyear15 Thank you for suggestion!
I see, what unique about this function is advantage is that it can execute multiple IBC operations at once in a single transaction execution, right?
Then, what is merit of it? I guess it can lower gas costs somehow, is this the point?

**Comment by lightyear15** [comment]
@siburu ,
yes exactly.
In principle it would be possible to send multiple state-changing messages all at once, lowering the transactions costs, waiting time,etc...

**Comment by bluele** [comment]
Note: currently, developers can implement such functions on contracts that inherit IBCHandler.
https://github.com/hyperledger-labs/yui-ibc-solidity/blob/main/contracts/core/25-handler/IBCHandler.sol

If there is a reason why this should be implemented in IBCHandler instead of in the derived contract, please open the issue again.
